$ENV:PATH = "C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common"
$ENV:Path=$ENV:Path+";C:\Program Files\dotnet\"
$ENV:Path=$ENV:Path+";C:\WINDOWS"
$ENV:Path=$ENV:Path+";C:\WINDOWS\System32\OpenSSH\"
$ENV:Path=$ENV:Path+";C:\WINDOWS\System32\Wbem"
$ENV:Path=$ENV:Path+";C:\WINDOWS\system32"
$ENV:Path=$ENV:Path+";D:\Users\masaaki\Desktop\Application\clnch/lib"
$ENV:Path=$ENV:Path+";D:\Users\masaaki\scoop\apps\luarocks\current\rocks\bin"
$ENV:Path=$ENV:Path+";D:\Users\masaaki\scoop\apps\nodejs\current"
$ENV:Path=$ENV:Path+";D:\Users\masaaki\scoop\apps\nodejs\current\bin"
$ENV:Path=$ENV:Path+";D:\Users\masaaki\scoop\apps\openjdk\current\bin"
$ENV:Path=$ENV:Path+";D:\Users\masaaki\scoop\apps\powershell\current"
$ENV:Path=$ENV:Path+";D:\Users\masaaki\scoop\apps\python\current"
$ENV:Path=$ENV:Path+";D:\Users\masaaki\scoop\apps\python\current\Scripts"
$ENV:Path=$ENV:Path+";D:\Users\masaaki\scoop\apps\rustup\current\.cargo\bin"
$ENV:Path=$ENV:Path+";D:\Users\masaaki\scoop\apps\volta\current\appdata\bin"
$ENV:Path=$ENV:Path+";D:\Users\masaaki\scoop\shims"

# this is last
$ENV:Path=$ENV:Path+";C:\Users\masaaki\AppData\Local\Microsoft\WindowsApps"
$ENV:Path=$ENV:Path+";C:\WINDOWS\System32\WindowsPowerShell\v1.0\"
# C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\Users\masaaki\AppData\Local\Microsoft\WindowsApps;C:\WINDOWS;C:\WINDOWS\System32\OpenSSH\;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\system32;D:\Users\masaaki\Desktop\Application\clnch/lib;D:\Users\masaaki\scoop\apps\luarocks\current\rocks\bin;D:\Users\masaaki\scoop\apps\nodejs\current;D:\Users\masaaki\scoop\apps\nodejs\current\bin;D:\Users\masaaki\scoop\apps\openjdk\current\bin;D:\Users\masaaki\scoop\apps\powershell\current;D:\Users\masaaki\scoop\apps\python\current;D:\Users\masaaki\scoop\apps\python\current\Scripts;D:\Users\masaaki\scoop\apps\rustup\current\.cargo\bin;D:\Users\masaaki\scoop\apps\volta\current\appdata\bin;D:\Users\masaaki\scoop\shims
